FROM rocker/tidyverse:latest
MAINTAINER "Carlos Zambrana-Torrelio" zambrana@ecohealthalliance.org
## Installs to help install
RUN apt-get update && apt-get install -y --allow-downgrades --allow-remove-essential --allow-change-held-packages --allow-unauthenticated --no-install-recommends --no-upgrade \
    curl \
    htop \
    imagemagick \
    libgsl-dbg \
    libgsl-dev \
    libglpk40 \ 
    libgtk2.0-dev \  
    libfftw3-dev \
    libx11-6 \
    libxss1 \
    libxt6 \
    libxext6 \
    libsm6 \
    libice6 \
    openssh-server \
    tcl8.6-dev \
    tk8.6-dev \
    pkg-config \
    xdg-utils \
    xvfb \
    x11-apps \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/ \
ENV DISPLAY :0
### R config and packages
RUN echo "CFLAGS=-w" >> /usr/local/lib/R/etc/Makevars.site \
  && echo "CXXFLAGS=-w"  >> /usr/local/lib/R/etc/Makevars.site \
  && echo "MAKEFLAGS=-j$(nproc)"  >> /usr/local/lib/R/etc/Makevars.site \
  && Rscript -e 'requireNamespace("BiocManager"); BiocManager::install();' \
  && Rscript -e 'requireNamespace("BiocManager"); BiocManager::install("EBImage")' \
## install from github 
  && installGithub.r -d s-u/unixtools \
## Compile R packages
  && install2.r --error --skipinstalled \
  easyPubMed \
  ggraph \
  ggthemes \
  gt \
  handlr \
  here \
  janitor \
  lemon \
  metaDigitise \
  metagear \
  metafor \
  patchwork \
  piggyback \
  prodigenr \
  revtools \
  robvis \
  scales \
  styler \
  suppdata \
  synthesisr \
  taxadb \
  tidygraph \
  && installGithub.r elizagrames/litsearchr \
  && installGithub.r elizagrames/topictagger \
  #&& installGithub.r lockedata/starters \
  #&& installGithub.r hrbrmstr/rdatainfo \
  #&& installGithub.r benmarwick/rrtools
  && R -e "update.packages(ask = FALSE)" \
  && rm -rf /tmp/downloaded_packages/ /tmp/*.rds /root/tmp/downloaded_packages
COPY --chown=rstudio rstudio-prefs.json /home/rstudio/.config/rstudio/rstudio-prefs.json