FROM rocker/tidyverse:latest
MAINTAINER "Carlos Zambrana-Torrelio" zambrana@ecohealthalliance.org
## Installs to help install
RUN apt-get update && apt-get install -y --allow-downgrades --allow-remove-essential --allow-change-held-packages --allow-unauthenticated --no-install-recommends --no-upgrade \
    curl \
    htop \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/

### R config and packages
RUN echo "CFLAGS=-w" >> /usr/local/lib/R/etc/Makevars.site \
  &&  echo "CXXFLAGS=-w"  >> /usr/local/lib/R/etc/Makevars.site \
  &&  echo "MAKEFLAGS=-j$(nproc)"  >> /usr/local/lib/R/etc/Makevars.site \
## install from github 
  && installGithub.r -d s-u/unixtools \
## Compile R packages
  && install2.r --error --skipinstalled \
  here \
  janitor \
  lemon \
  patchwork \
  piggyback \
  scales \
  styler \
  taxadb \
  && installGithub.r elizagrames/litsearchr \
  && R -e "update.packages(ask = FALSE)"  \
  && rm -rf /tmp/downloaded_packages/ /tmp/*.rds /root/tmp/downloaded_packages


